version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

    restart: always
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
      - "9222:9222"
    volumes:
      - ./dist/:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    links:
      - mongo
